-- URALSTORE shared shifts and motivation v1.
-- Apply once in the existing Supabase project's SQL Editor.

begin;

create table public.staff_employees (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) between 1 and 120),
  daily_rate numeric(12,2) not null default 0 check (daily_rate >= 0),
  sort_order integer not null default 0,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table public.staff_shifts (
  employee_id bigint not null references public.staff_employees(id) on delete cascade,
  shift_date date not null,
  status text not null check (status in ('rs','os','zo','off')),
  closed boolean not null default false,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  primary key (employee_id,shift_date),
  check (not closed or status in ('rs','os','zo'))
);

create table public.staff_motivation_events (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.staff_employees(id) on delete cascade,
  event_date date not null,
  event_type text not null check (event_type in ('bonus','penalty')),
  amount numeric(12,2) not null check (amount > 0),
  reason text not null check (length(trim(reason)) between 1 and 300),
  notes text not null default '' check (length(notes) <= 2000),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create index staff_shifts_date_idx on public.staff_shifts(shift_date);
create index staff_motivation_events_date_idx on public.staff_motivation_events(event_date);
create index staff_motivation_events_employee_idx on public.staff_motivation_events(employee_id);

alter table public.staff_employees enable row level security;
alter table public.staff_shifts enable row level security;
alter table public.staff_motivation_events enable row level security;

create or replace function public.has_app_access()
returns boolean
language sql
security definer
set search_path=''
stable
as $$
  select exists(
    select 1
    from public.app_access_sessions s
    where s.user_id=(select auth.uid())
      and s.active
      and s.access_role in ('staff','admin')
  );
$$;

revoke all on function public.has_app_access() from public,anon,authenticated;
grant execute on function public.has_app_access() to authenticated;

grant select,insert,update,delete on public.staff_employees to authenticated;
grant select,insert,update,delete on public.staff_shifts to authenticated;
grant select,insert,update,delete on public.staff_motivation_events to authenticated;
grant usage,select on sequence public.staff_employees_id_seq to authenticated;
grant usage,select on sequence public.staff_motivation_events_id_seq to authenticated;

create policy staff_employees_shared_access on public.staff_employees
for all to authenticated
using (public.has_app_access())
with check (public.has_app_access());

create policy staff_shifts_shared_access on public.staff_shifts
for all to authenticated
using (public.has_app_access())
with check (public.has_app_access());

create policy staff_motivation_shared_access on public.staff_motivation_events
for all to authenticated
using (public.has_app_access())
with check (public.has_app_access());

do $$
begin
  if not exists(
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='staff_employees'
  ) then
    alter publication supabase_realtime add table public.staff_employees;
  end if;
  if not exists(
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='staff_shifts'
  ) then
    alter publication supabase_realtime add table public.staff_shifts;
  end if;
  if not exists(
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='staff_motivation_events'
  ) then
    alter publication supabase_realtime add table public.staff_motivation_events;
  end if;
end $$;

notify pgrst,'reload schema';
commit;
